# Tomcat 端口
server:
  port: 9191

spring:
  # Druid Pool 运行环境
  profiles:
    # 运 行 环 境
    active: druid
        # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  jpa: 
    open-in-view: true
# mybatis 配置
mybatis:
  # 配 置 扫 描
  mapper-locations: classpath*:**/xml/**.xml
  # 别 名 扫 描
  type-aliases-package: com.yuqiao

# Page Helper
pagehelper:
  # 方 言
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

# logging 配置
logging:
  # 日 志 级 别
  level:
    # 日 志 包 配 置
    com.yuqiao.*: DEBUG



